---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: home-os
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      nonfree: negativo17
    group-install:
      packages:
        - virtualization
    install:
      packages:
        - nvim
        - kitty
        - fastfetch
        - btop
        - fish
        - https://github.com/dahui/z13ctl/releases/download/v1.3.1/z13ctl_1.3.1_linux_amd64.rpm
        - steam
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: kargs
    arch: x86_64
    kargs:
      - amdgpu.dcdebugmask=0x410


  # - type: default-flatpaks
  #   configurations:
  #     - notify: true # Send notification after install/uninstall is finished (true/false)
  #       scope: system
  #       # If no repo information is specified, Flathub will be used by default
  #       install: # system flatpaks we want all users to have and not remove
  #         - org.mozilla.firefox
  #         - org.gnome.Loupe
  #     - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
